services:
  - type: web
    name: broodinnox-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn python_enterface:app --bind 0.0.0.0:$PORT
